services:
  - type: web
    name: superstudent
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SITE_PASSWORD
        sync: false
      - key: TEACHER_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: RENDER
        value: "true"
